name: Deploy to ECR

on: 
  push:
    branches: [ main ]

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

   
    steps:

    - name: Check out code
      uses: actions/checkout@v4

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1

    - name: Build, test, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: project-ecr
        IMAGE_TAG: 1
        # IMAGE_TAG: ${{ github.run_number }}
      run: |
        ls -ltra

        # Docker build command
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:app-v$IMAGE_TAG -f Dockerfile .
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:db-v$IMAGE_TAG -f Dockerfile_mysql .

        # Create network
         docker network create -d bridge --subnet 172.18.0.0/24 --gateway 172.18.0.1 my_network
        
        docker network ls
        sleep 10

        export DBPWD=wordpass
        export ECR=$ECR_REGISTRY/$ECR_REPOSITORY

        # Deploy database
        docker run -d --name db -e MYSQL_ROOT_PASSWORD=wordpass $ECR:db-v$IMAGE_TAG
        sleep 10
        docker ps


        export DBHOST=127.0.0.1
        export DBPORT=3306
        export DATABASE=employees
        export DBNAME=employees
        export DBUSER=root
        export APP_COLOR=blue

        # Deploy app when database is ready
        docker run -d --name app -p 81:81 -e DBHOST=$DBHOST -e DBPORT=$DBPORT -e DBUSER=$DBUSER -e DBPWD=$DBPWD -e APP_COLOR="blue" $ECR:app-v$IMAGE_TAG
        
        docker ps
        docker images
        echo "Pause for 10 seconds to ensure container is deployed"
        docker inspect db
        sleep 10
        
        # Test if app is functioning
        curl localhost:81 -vvv

        # Push images when successful
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:app-v$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:db-v$IMAGE_TAG
